### ISSUE TITLE
Overview - Link to "edit the configuration file" not working

### ISSUE THREAD

**Issue by paulverkooijen** [ptarmiganlabs/butler-docs#14]
Gets you to https://butler.ptarmiganlabs.com/docs/getting-started/overview/setup

Not found
Oops! This page doesn't exist. Try going back to our home page.

**Comment by mountaindude** [comment]
@paulverkooijen Thanks for reporting this, much appreciated.

The broken link has been fixed, should be online in a minute or two.

On a related note, the Butler docs site is currently lagging a couple of versions behind the Butler version that is [available on GitHub](https://github.com/ptarmiganlabs/butler/releases).

What's missing from the doc site is mainly info about how to use Butler with New Relic.
Specifically how to send failed reload alerts (incl script logs for the failed reload!) to New Relic.
An updated doc site should be available in a week or two.

https://ptarmiganlabs.com is also a good place to get info on the latest about the various Butler tools and [Ctrl-Q.](https://github.com/ptarmiganlabs)
[Sign up for the newsletter](https://ptarmiganlabs.com/#/portal/signup) and you'll get news to your inbox when significant new releases are done.
